CC = gcc

CFLAGS = -Wall -Werror -pthread

CLIENT_SRC = Client.c
SINGLETHREAD_SRC = SingleThreading_Server.c
MULTITHREAD_SRC = MultiThreading_Server.c
USINGSYSTEM_SRC = UsingSystem_Server.c

CLIENT_EXE = client
SINGLETHREAD_EXE = singlethread
MULTITHREAD_EXE = multithread
USINGSYSTEM_EXE = systemthread

all: $(CLIENT_EXE) $(SINGLETHREAD_EXE) $(MULTITHREAD_EXE) $(USINGSYSTEM_EXE)

$(CLIENT_EXE): $(CLIENT_SRC)
	$(CC) $(CFLAGS) -o $(CLIENT_EXE) $(CLIENT_SRC)

$(SINGLETHREAD_EXE): $(SINGLETHREAD_SRC)
	$(CC) $(CFLAGS) -o $(SINGLETHREAD_EXE) $(SINGLETHREAD_SRC)

$(MULTITHREAD_EXE): $(MULTITHREAD_SRC)
	$(CC) $(CFLAGS) -o $(MULTITHREAD_EXE) $(MULTITHREAD_SRC)

$(USINGSYSTEM_EXE): $(USINGSYSTEM_SRC)
	$(CC) $(CFLAGS) -o $(USINGSYSTEM_EXE) $(USINGSYSTEM_SRC)

clean:
	rm -f $(CLIENT_EXE) $(SINGLETHREAD_EXE) $(MULTITHREAD_EXE) $(USINGSYSTEM_EXE)

.PHONY: all clean